project:
  type: website
  output-dir: docs

website:
  title: "Tiana Ho"
  navbar:
    left:
      - href: index.qmd
        text: home
      - text: projects
        menu:
          - text: "sql project"
            href: sql_project.qmd
          - text: "JobTrackeR"
            href: job_tracker.qmd
          - text: "text analysis"
            href: text_analysis.qmd
          - text: "article analysis"
            href: article_analysis.qmd
          - text: "econometrics pp"
            href: econ_pp.qmd
          - text: "econometrics rp"
            href: econ_rp.qmd
          - text: "econometrics cp"
            href: econ_cp.qmd
      - href: motion.qmd
        text: motion
      - href: life.qmd
        text: life

format:
  html:
    theme: cosmo
    css: styles.css